name: Build and Release Executables

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: 

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: unsealer-linux
            asset_name: unsealer-linux-x64
          - os: windows-latest
            artifact_name: unsealer.exe
            asset_name: unsealer-windows-x64.exe
          - os: macos-latest
            artifact_name: unsealer
            asset_name: unsealer-macos-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install System Dependencies
        if: runner.os != 'Windows'
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y libzbar0
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install zbar
          fi

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pyinstaller

      - name: Build with PyInstaller
        shell: bash
        run: |
          SEP=":"
          if [[ "${{ runner.os }}" == "Windows" ]]; then SEP=";"; fi
          
          pyinstaller --onefile --name unsealer \
            --clean \
            --add-data "src/unsealer/samsung/schema.json${SEP}unsealer/samsung" \
            src/unsealer/__main__.py

      - name: Rename Artifact
        shell: bash
        run: |
          cd dist
          mv ${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: dist/${{ matrix.asset_name }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./assets

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./assets/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 